//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam_sem3.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Exam
    {
        public int ID { get; set; }
        [Display (Name = " Exam Subject")]
        public string Subject { get; set; }
        [Display(Name = " Start Time")]
        public System.TimeSpan StartTime { get; set; }
        [Display(Name = " Exam Date")]

        public System.DateTime ExamDate { get; set; }
        [Display(Name = " Duration")]

        public int Duration { get; set; }
        [Display(Name = " Class Room")]

        public int ClassRoom { get; set; }
        [Display(Name = " Faculty")]

        public int Faculty { get; set; }

        public int Status { get; set; }
    }
}
